### ISSUE TITLE
Possibly predict values in space domain?

### ISSUE THREAD

**Issue by KehanLong** [NFFT/nfft#104]
Hi,

I am trying to solve the following problem with NFFT: 

Given an matrix of size N by N with M known values, I am trying to predict the unknown values of the matrix. Firstly, I use the nfft_adjoint method to transform the input to N by N frequency matrix. Then, I plan to use nfft_trafo to reconstruct the values in space domain. However, the reconstructed result are still only the M known values. 

Hence, I wonder, is there a method I can use to reconstruct the whole matrix? Will the normal FFT work here, as long as we already got the uniform n by n frequencies? 

Any suggestions/replies are appreciated.

**Comment by tvolkmer** [comment]
As mentioned in the [FAQ,](https://www-user.tu-chemnitz.de/~potts/nfft/faq.php) an inverse NFFT has to be used instead of `nfft_adjoint`, see also [Inversion](https://www-user.tu-chemnitz.de/~potts/nfft/infft.php).
