### ISSUE TITLE
Even bandwith in NFCT and NFST

### ISSUE THREAD

**Issue by nklb** [NFFT/nfft#105]
Hi,

according to your definition of the non equidistant trigonometric transforms [here](https://www-user.tu-chemnitz.de/~potts/nfft/fast_trig.php) there shouldn't be a problem if the bandwidth N is odd. 

But when I run an NFST(check) for an NFST plan with odd N I obtain the message 
~~~
Error in nfst module: polynomial degree N has to be even
~~~
Same for NFCT. This can be easily reproduced by compiling and running `/examples/nfst/simple_test.c` with an odd N. It seems though that transforms for odd N are correctly computed if I don't let the check stop the function.

**Comment by michaelquellmalz** [comment]
This error message seems to be unnecessary. I cannot see any problem in the NFCT/NFST with odd degree N.

However, the plain NFFT works only for even degree N.
