### ISSUE TITLE
Unable to determine floating-point epsilon

### ISSUE THREAD

**Issue by runburg** [NFFT/nfft#107]
I'm trying to compile NFFT3 to use with pyNFFT.  I'm on macOS Catalina.

When I go to configure with ```./configure --enable-all --enable-openmp``` (I also point it to my FFTW install), I get 
```
checking for floating-point epsilon as per length of mantissa... unknown
configure: error: Unable to determine floating-point epsilon.
```
I am not sure how to address this. Any help with Mac install?

Thanks!

**Comment by tvolkmer** [comment]
Dear runburg,

without any further information (`config.log`), it is hard to give any advice.

We compile the Matlab/Octave MEX files using MacPorts and GCC.

Best,
Toni
