### ISSUE TITLE
Where are the install instructions?

### ISSUE THREAD

**Issue by stringhamc** [NFFT/nfft#11]
I can't find the install instructions in the latest git version.

**Comment by ghisvail** [comment]
```
./bootstrap.sh
./configure --<your build options, use configure -h to list them all>
make
make install
```

Sure the README could make these steps explicit.

**Comment by stringhamc** [comment]
Thanks, I eventually figured that out. I understand that is the typical
process, but at first I avoided using the bootstrap.sh script because
inside it says to follow the install instructions under doc/tutorial...
which also don't exist. Sorry I'm not being more helpful and submitting a
pull request on updated documentation. Thanks for the help!

**Comment by ghisvail** [comment]
You brought up a good point though. Every single github project I have personally contributed to do provide some build and installation instructions in their README.

**Comment by jenskeiner** [comment]
We'll fix that. Thanks.

**Comment by tvolkmer** [comment]
The install instructions were added to the README file.
