### ISSUE TITLE
NFSFT crashes with new GCC

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#11]
When compiled with GCC 4.9.0 and newer under Windows 7 x64, the NFSFT library of NFFT 3.3 chrashes.
The file `nfsft_benchomp.exe` crashes already for the single-thread version and gives the following error:
```
WARNING: Detailed time measurements for NFSFT are not activated.
For more detailed plots, please re-run the configure script with options
--enable-measure-time --enable-measure-time-fftw --enable-nfsft --enable-openmp
and run "make clean all"

1 2 3 4
nfsft_benchomp_createdataset.exe 0 1024 1000000 > nfsft_benchomp_test.data
tr_adj=0, N=1024, M=1000000
nfsft_benchomp_detail_single.exe 2 0 2048 5 < nfsft_benchomp_test.data > nfsft_b
enchomp_test.out
ERROR nfsft_benchomp_detail_single.exe 2 0 2048 5 < nfsft_benchomp_test.data > n
fsft_benchomp_test.out: -1073741571 not 0
```
In the Matlab interface, you get the error `Error using nfsftmex. Not enough memory.` if you execute the NFSFT with polynomial N>16.

Note that this error only occurs with the new NFFT 3.3 and the new GCC 5.3. Both the NFFT 3.3 compiled with GCC 4.8.1 as well as the NFFT 3.2.4 compiled with GCC 5.3 work fine.

**Comment by jenskeiner** [comment]
I can reproduce the issue using GCC 4.8.5 and 5.3.0. I reckon this could be related to the size of int and/or INT on 64 bit machines, but I need to have a closer look. Different versions of GCC might handle implicit type conversions differently.

**Comment by jenskeiner** [comment]
I've added a temporary workaround for the issue. Can anyone confirm it's fixed now (on the develop branch)?

**Comment by michaelquellmalz** [comment]
Yes, the nfsft from the develop branch works with gcc 5.3.0. 😊

**Comment by jenskeiner** [comment]
Closing this one.
