### ISSUE TITLE
NFFST projection.m runs out of memory

### ISSUE THREAD

**Issue by PabloBrubeck** [NFFT/nfft#12]
The Matlab script simple_test.m runs well on my computer, but when I try to execute projection.m Matlab displays an "out of memory" message that aborts the execution.

**Comment by michaelquellmalz** [comment]
Could you please specify which version of NFFT, what compiler in which version you used and with which parameters you ran the configure script and your platform (Linux/Windows 32/64 bit)?

**Comment by PabloBrubeck** [comment]
NFFT v 3.3.0
gcc 4.9.2
Ubuntu 15.04 64 bit

This is the configure parameters
./configure --enable-all --with-matlab=/usr/local/MATLAB/MATLAB_Production_Server/R2015a

This is the complete error message shown by Matlab:

Error using nfsftmex
Not enough memory.
Error in nfsft_precompute (line 30)
nfsftmex('precompute',N,kappa,nfsft_flags,fpt_flags)
Error in projection (line 33)
nfsft_precompute(max(Nv),kappa);

**Comment by michaelquellmalz** [comment]
This is the same issue I posted [before](https://github.com/NFFT/nfft/issues/11) for Windows. The NFSFT form NFFT 3.3 seems to have this error when compiled with GCC 4.9.0 and newer. It should work with GCC 4.8.1. Maybe you could try this before someone finds the bug (either in NFFT or GCC).

**Comment by PabloBrubeck** [comment]
Building with gcc 4.8 fixed the issue. Thank you

**Comment by jenskeiner** [comment]
Closing this one. Progress will be tracked in #11.
