### ISSUE TITLE
[Conventions] Rename or softlink to CONTRIBUTING.md?

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#123]
As the `CONVENTIONS.md` was enriched with new conventions, recently, due to the ongoing discussion in #120, it becomes more and more a contribution guideline for developers.

Since GitHub defines in its Community Standards that projects should provide exactly such a guideline named `CONTRIBUTING.md` (see Insights > Community for the full checklist), I would like to suggest a renaming of the file or at least creating a matching softlink to it.  Thereby, this community standard would be fulfilled and the role of `CONVENTIONS.md` would then be honoured as such since, due to the Community Standards, one expects -- more or less -- to find the conventions in a file named `CONTRIBUTING.md`.

Softlinking or renaming the file would have the further benefit that the conventions are listed on the project's "Welcome Page" since the system recognises it as contribution guideline then.  This is also an aspect of quality of a project and, hence, worth to discuss it.

**Comment by kevinmatthes** [comment]
I tested the proposed change in one of my repositories and noticed that the `CONTRIBUTING.md` will not be shown on the project's "Welcome Page".  This behaviour is complementary to GitLab due to which I expected this feature, I am sorry.

Anyway, the file name triggered the completion of one of GitHub's Community Standards which might be still interpreted as one possible measure of quality.  Hence, is it worth softlinking or renaming `CONVENTIONS.md` as suggested?

**Comment by michaelquellmalz** [comment]
This would be a rather cosmetic change, so I am closing this one here.
