### ISSUE TITLE
[README] [Citing] Provide a BibTeX database entry

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#124]
Some projects, like [SuperCages](https://github.com/cordafab/SuperCages), provide a separate BibTeX database entry in order to ensure the intended style of citing.

The referenced project provides it in the README.

Since our `README.md` also contains a citing guideline, I would like to ask if we rather should

* provide a BibTeX entry as a separate file in the repository (e. g. in the `support` or `doc` directory) and reference it in the `README.md` additionally.
* provide the BibTeX entry's source code in our `README.md`.
* do both (separate file in repository *and* source code in `README.md`).

This would make citing this project in the intended form easier since interested users could use these prepared BibTeX database entries as a utility therefore.

What do you think about this?

**Comment by michaelquellmalz** [comment]
Since it is jor just one reference, we could easily add it to the readme.

**Comment by michaelquellmalz** [comment]
Done.
