### ISSUE TITLE
[configure] Change of shebang

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#126]
As already discussed in #122, the shebang of a shell script should be chosen as general as possible in order to avoid unintended behaviour of the build routine on machines where the actual installation path of Bash differs.

Since `./configure` is a result of the execution of `./bootstrap.sh` which actually requires Bash itself, we should think about adjusting the shebang of `./configure` to Bash as language since we already need it just to create this file.

Furthermore, the current shebang, `#! /bin/sh`, contains a rather obsolete space between the exclamation mark and the path which may cause problems.  For instance, VSCodium is unable to consider this file syntactically correct and, hence, lists 919 errors, 81 warnings (plus 130 further errors and warnings which are suppressed) originating from this file.  On the other hand, `./bootstrap.sh` does not render any warning.

Despite the possibility that this might be just a temporary bug of the IDE or one of its plugins which can be fixed in a future version, we should discuss if we really need this generality of `./configure`.  For instance, it contains several setting lines just to ensure compatibility with Bash.  Since it is a temporary file created during the execution of `./bootstrap.sh`, which only works with Bash, this generality (`sh` instead of `bash` as environment variable) is in my opinion not required.

What do you think about this topic?

**Comment by michaelquellmalz** [comment]
This shebang is automatically generated by autoconf in order to be compatible with many system. Changing it seems to be not supported by autoconf.
