### ISSUE TITLE
[README.md] Checklist for required further software?

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#127]
In order to enhance the build process, we could a add a list of required software in order to build this project.

Users who are interested in cloning and building this project could then use this list as a checklist whether they already have all dependencies (mandatory and optional ones) installed on their machines.

In my opinion, the best place for such a checklist would be a section within the `README.md` since it is shown directly on the "Welcome Page" of our project.  Alternatively, we could also provide it as a simple text file or another Markdown file in the `support` directory.

**Comment by michaelquellmalz** [comment]
I agree, we should mention it. At least the requirement of the FFTW is already mentioned in the readme. What I currently think of (maybe I forget something):

For just building from the release we do require `make` and some compiler like `gcc`. 

For bootstrap.sh we additionally require `autoconf`, `automake`, and `libtool`. We need `cunit` for the unit tests. For the release we need `doxygen`, `doxygen-latex` and `graphviz`. The respective interfaces require Matlab or Octave.

**Comment by kevinmatthes** [comment]
Okay, I would therefore prepare an according checklist.

Shall I write it down into a separate Markdown document or directly into `README`?  Furthermore, shall I push to a new branch?

**Comment by kevinmatthes** [comment]
Another point are the configuration for `fftw3` when built from an official source package and the required packages therefore.  The `README` already states one required flag but could be useful if the required flags for `NFFT` would be named in detail.

In case this should be added, as well, I would write down these information in the respective software checklist.

Which configuration flags for `fftw3` ensure an optimal build of `NFFT`?

**Comment by kevinmatthes** [comment]
The minimum flags for `fftw3`'s `./configure` are -- as far as I experienced it -- as follows:

* `--enable-shared`
* `--enable-openmp`
* `--enable-threads`

Would it be useful to add them to the `README`?
