### ISSUE TITLE
[README.md] Relevance of the softlink

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#128]
This repository contains a softlink to its `README.md` in order to solve an issue with a former version of it.

As far as I can see, this softlink is not required anymore since the "Welcome Page" of the project directly shows `README.md`.  This softlink might originate from a previous version of GitHub where the file extension might have led to problems, but nowadays, the Markdown extension is rather standard than exception.

Hence, I would like to suggest to check whether the softlink could be a duplicate and, thereby, obsolete. This could be done by creating a new branch and removing the softlink for testing purposes.  If the "Welcome Page" still works properly, the softlink has proven obsolete.  If not, the branch can just be removed in order to restore the softlink.

**Comment by kevinmatthes** [comment]
I just pushed the test on a new branch, `feature/remove-softlink` to the repository.  The "Welcome Page" still works properly.  Hence, the softlink does not need to kept anymore and has proven truely a duplicate of `README.md`.

Shall the softlink be kept anyway and the test be revoked by deleting the branch?  Or can this feature be added to one of the active branches?

**Comment by kevinmatthes** [comment]
The softlink is still required by almost all makefiles.  The only exceptions the ones from the Julia directory.

I will upload a patch for that.

**Comment by kevinmatthes** [comment]
It seems as if the softlink would be included into the build routine in a way which makes a future removal a bit complicated.

I would like to suggest to remove it from the build routine when the latter one is going to be maintained the next time.

**Comment by michaelquellmalz** [comment]
As the softlink does not cause any problems, we can just keep it for now.
