### ISSUE TITLE
Unnecessary calculation?

### ISSUE THREAD

**Issue by kaatish** [NFFT/nfft#13]
In file nfft/kernel/solver/solver.c
function static void solver_loop_one_step_cgnr_complex(X(plan_complex) *ths)
line 266-269
```
  if(ths->flags & PRECOMPUTE_WEIGHT)
    ths->dot_r_iter = Y(dot_w_complex)(ths->r_iter,ths->w,ths->mv->M_total);
  else
    ths->dot_r_iter = Y(dot_complex)(ths->r_iter, ths->mv->M_total);
```
Is the calculation of dot_r_iter necessary?
I do not see it being used anywhere inside this function.

**Comment by tvolkmer** [comment]
Thank you for your comment on this issue.

I think only the CGNE solver in kernel/solver/solver.c uses dot_r_iter directly.

However, code which uses the solver module might use this residual value as a stopping criterion (or just to display the current status/success of the solver iteration), e.g.:
- examples/solver/simple_test.c lines 133 and 147, printf
- examples/solver/glacier.c line 99, printf
- applications/iterS2/iterS2.c line 518, printf
- (applications/radon/inverse_radon.c line 220, stopping criterion, however commented out)
- applications/mri/mri2d/reconstruct_data_2d.c lines 129 and 131, stopping criterion + printf
- applications/mri/mri2d/reconstruct_data_inh_2d1d.c lines 186 and 188, stopping criterion + printf
- ...
