### ISSUE TITLE
[Build routine] Progress bar for visualisation?

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#132]
How about adding a progress bar such as the one `apt` has to the build routine?  This would be an enhancement for the users who build `NFFT` for the first time since they would know what is already done in comparison to the whole build step.

As a measure of progress, I would like to suggest the count of already executed instructions.

**Comment by michaelquellmalz** [comment]
I do not think that this is an important feature because the full compilation usually takes less than 5 minutes and the duration of the different steps highly depends on the system (e.g. the checks in the configure script work much faster on linux than on msys2 in windows).
