### ISSUE TITLE
osx binaries

### ISSUE THREAD

**Issue by mischmi96** [NFFT/nfft#133]
I have some trouble getting our Julia interface NFFT3.jl to work on osx. Is someone able to provide me with the julia binaries compiled on the latest osx?

**Comment by tvolkmer** [comment]
The latest ones should be here: https://www-user.tu-chemnitz.de/~potts/nfft/download.php#julia

**Comment by tknopp** [comment]
For me `NFFT3.jl` on OS X just works. Probably this issue can be closed.

**Comment by mischmi96** [comment]
Thanks! Still wondering why the CI fails though ...

**Comment by michaelquellmalz** [comment]
That might be a problem because the binaries require AVX2, which is available on most Intel CPUs since 2013. I am not sure on which hardware the CI runs (maybe they use some virtualization, which could cause the problems).
