### ISSUE TITLE
Interface with Python

### ISSUE THREAD

**Issue by mdarmstr** [NFFT/nfft#135]
I would like to develop an interface for this library using Python, using something like the Numpy C API.

**Comment by passscoed** [comment]
We would be interested in such a Python interface and it would be nice if you would implement it.

**Comment by michaelquellmalz** [comment]
For an example, you could look at the C interface for Julia (see `julia/nfft/libnfftjulia.c`). 

Furthermore, you might have a look at the two following external projects: There is some existing code for a Python interface of the `fastsum` class of the NFFT in [dominikbuenger/FastAdjacency](https://github.com/dominikbuenger/FastAdjacency/blob/master/fastadj/core.c).
Moreover, there is a Python NFFT wrapper [pynfft](https://github.com/pyNFFT/pyNFFT) but it was last updated for NFFT 3.3 and I am not sure if that would fit your needs.

**Comment by mdarmstr** [comment]
Thank you for your suggestions. I'm interested in interfacing with the latest version of the repository, for the sake of long-term stability.

**Comment by mdarmstr** [comment]
I am still interested in continuing this project, but the approach of using Python is not being considered by my place of employment at the moment. Happy to share what I have with anyone wishing to collaborate.

**Comment by michaelquellmalz** [comment]
There is now a new Python wrapper called pyNFFT3 maintained within this project, see [https://github.com/NFFT/pyNFFT3](https://github.com/NFFT/pyNFFT3). It currently supports the NFFT, fastsum and the trigonometric transforms NFCT and NFST. So I am closing this one.
