### ISSUE TITLE
applications\fastsum\fastsum_matlab produces wrong results in Windows

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#14]
The `fastsum_matlab.c` called by `fastsum_test.m` reads zeros as inputs for x,y,alpha. This error occurs only in Windows and nfft-3.3 but not in nfft-3.2.4. The reason for this seems to be the scanf format string
   `#  define __FR__ "%la"`
in the `infft.h` include file. Apparently, Windows does not support `%a` for `scanf`,  see also [C scanf %la returns 0](http://stackoverflow.com/questions/23900921/c-scanf-la-returns-0).

@jenskeiner : Is there a reason for using `%la` instead of `%le`? Maybe we can replace this macro as suggested. Do you think there might be any possible issues against this replacement?

**Comment by jenskeiner** [comment]
We can change the format string to %le if they are all equivalent for sscanf anyway. Does this actually fix the issue? We also need to check float and long double variants.

**Comment by tvolkmer** [comment]
fixed in develop branch by @michaelquellmalz
