### ISSUE TITLE
Problem compiling matlab/nfft

### ISSUE THREAD

**Issue by magland** [NFFT/nfft#14]
Using Ubuntu
Did ./bootstrap.sh, then .configure, then make (did not do make install)
Ran make in matlab/nfft
"No rule to make target '../../libnfft3_matlab.la'"

Thanks!

**Comment by magland** [comment]
Okay, I was able to remove that error by running
>> make libnfft3_matlab.la
from the top directory.

However, I don't see any mex files. Not sure how to create nfft3mex for use in matlab

**Comment by magland** [comment]
Resolved: I figured out to do this:

> ./configure --with-matlab-arch=glnxa64 --with-matlab=~/MATLAB/R2015a/ --enable-all --enable-openmp

Hope it helps somebody else.

**Comment by jenskeiner** [comment]
Which options did you use with configure? It will only compile the mex if it has been able to find a usable Matlab installation.

**Comment by magland** [comment]
You are right. And see my last reply.

**Comment by tvolkmer** [comment]
The configure script does not search for the Matlab installation on its own. I'm closing this issue.

**Comment by jenskeiner** [comment]
Ok. Went into the wrong inbox. My bad.
