### ISSUE TITLE
configure fails on Linux with MATLAB r2015b and r2016a

### ISSUE THREAD

**Issue by tvolkmer** [NFFT/nfft#17]
My commit [6fd86d9](https://github.com/NFFT/nfft/commit/6fd86d9e857668aa9ce6f0119253427b1d77a0a4), which fixed an issue with configure and MATLAB on Windows, causes the configure script to fail on Linux with MATLAB r2015b and r2016a.

**Comment by tvolkmer** [comment]
@michaelquellmalz: Would you please check if the configure script and compilation still work on Windows after my commit 540944c.

**Comment by michaelquellmalz** [comment]
Yes, it works in Windows.
