### ISSUE TITLE
Bump soversion as a result of major API changes

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#2]
Right now, building the nfft-3.3 branch produces a shared library with the same soversion (1.0.0) as the nfft-3.2 which is currently released and packaged. However, version 3.3 introduces some major API changes, which are likely to break anything linked with 3.2 like my Python bindings for instance. As a result, it would be wise to bump the soversion to 2.0.0 to explictly flag version 3.3 as backward incompatible.

**Comment by jenskeiner** [comment]
Done.
