### ISSUE TITLE
`make check` crashes on windows

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#20]
Even after the fix [d8da83e](https://github.com/michaelquellmalz/nfft/commit/d8da83e250673f5db2cb6133b60723039b7850ed), the execution of checkall crashes after the output
`$ ./checkall_threads.exe
check_1d_direct_file:
data/nfft_1d_1_1.txt            d = 39450, N = [4653152, 0    , 4653152, 0    , 4882432, 0    , 819200, 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , `
this goes on for a while and then
` , 0    , 0    , 0    , 0    , 0    , 0    ], M = 0     nthreads = 4, init_guru ()`

**Comment by michaelquellmalz** [comment]
I added a fix in the pull request #21 .
@tvolkmer  Could you check if `make check` still works in linux with the relative paths?

**Comment by tvolkmer** [comment]
We are going to fix this issue in the branch [bugfix/make-check-windows](https://github.com/NFFT/nfft/compare/bugfix/make-check-windows).

**Comment by michaelquellmalz** [comment]
`make distcheck` now works for me in windows in bugfix/make-check-windows.

**Comment by tvolkmer** [comment]
`make check` and `make distcheck` work for me on Linux openSUSE 13.1

@jenskeiner Would you please also verify this and have a look at the commits?

**Comment by tvolkmer** [comment]
Fixed in branch develop
