### ISSUE TITLE
Testsuite failures on selected architectures with 3.3.1

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#24]
Hi Jens,

As promised, I have refreshed the Debian packaging with the latest stable release. Some architectures fail to pass the test suite as we expected. The build status for all architectures is available [here](https://buildd.debian.org/status/package.php?p=nfft). You can access the respective log by clicking on `Build-Attempted`.

Thanks,
Ghis

**Comment by jenskeiner** [comment]
Hi Ghis,

thanks for updating the Debian packaging. I have checked the build failures. Most of them are easy too fix with a small update to some thresholds.

But there's also one issue that might be a bit more involved. There's a failure on `mips64el` when testing `x(bessel_i0)`. We use a rational Chebyshev approximation on the interval `[0,15]` and it doesn't seem to be accurate enough near `x = 15` -- but only when `long double` is a quadruple precision data type, and not just extended precision as e.g on x86.

For quadruple precision, we use a distinct set of coefficients for the approximation that have been generated with Mathematica to satisfy the desired error bounds. We could be facing two different problems here:

1. The coefficients do not provide for the necessary accuracy.
2. We fail to distinguish the extended precision/quadruple precision case correctly, i.e. we use an incorrect set of coefficients.

It should be possible to fix 1. by tweaking the coefficients just a little. I could do that. But we could also face 2. in which case we would need to fix our detection of floating-point characteristics.

Is it possible to build the package on the problematic architecture alone? To distinguish 1. and 2., we might need to add some debug output temporarily, so we can be sure what the problem actually is. Also, we might need to run a handful of those tests as I don't have access to this architecture myself. Can you think of other ways of testing on the affected architecture?

Cheers,


Jens

**Comment by ghisvail** [comment]
Is it possible to build the package on the problematic architecture alone?

Yes. I can try out patches on debomatic for selected architectures (mips64el included) and get detailed build logs like on the official builders.

Let me know if you have patches you would like to test.

**Comment by jenskeiner** [comment]
Cool, will let you know when I have a fixed version. I'm thinking about rewriting the bessel_i0 code, so it may take a bit longer than just tuning the constants.

**Comment by ghisvail** [comment]
It would be nice to have a quick-fix first (at least for the packaging) since the current failures prevent NFFT to migrate to `testing`.

**Comment by jenskeiner** [comment]
I'll do my best, but even that may take time depending on how hard it is to find a better approximation. It's top of the list anyway.

**Comment by ghisvail** [comment]
Alright, good luck with that. Keep me posted.

**Comment by jenskeiner** [comment]
Hi Ghislain,

I have created a new tag, `3.3.2rc1`. I have adjusted a few threshold slightly. This should fix most problems. Also, I have changed the way how we calculate `bessel_i0` when `long double` is a true double precision datatype and `x <= 15`. This should fix the remaining issue of inaccurate approximation in that special case. However, we will only see if this works when we test on `mips64el` architecture.

Could you test Debian build again with the new tag and let me know if there's still issues? Thanks.

**Comment by ghisvail** [comment]
> Could you test Debian build again with the new tag and let me know if there's still issues?

The [arm64 build](http://debomatic-arm64.debian.net/distribution#unstable/nfft/3.3.2~rc1-1/buildlog) is still failing.

**Comment by jenskeiner** [comment]
But it’s progress. There’s one case remaining in bessel_i0, but my changes actually fixed it for x <= 15. Will now work on the remaining case.

**Comment by jenskeiner** [comment]
I will need at least until next weekend to fix the remaining case. But I hope to be able to set up qemu with a comparable architecture so I can test before creating another tag.

**Comment by ghisvail** [comment]
No problem. The package will sit happily in `unstable` whilst you work on this. Thanks.

**Comment by jenskeiner** [comment]
I can now run Ubuntu on arm64 with the help of qemu, so I'm actually able to verify changes for that arch. Expect another tag soon.

**Comment by ghisvail** [comment]
Awesome, thanks for the update.

**Comment by jenskeiner** [comment]
I have created a new tag, `3.3.2rc2`. This should do the trick for arm64.

**Comment by ghisvail** [comment]
As an update on this, we had `powerpc` and `ppc64el` failing the testsuite for long-double with very off results. @jenskeiner acknowledged the issue to me by email privately.

Meanwhile, I have disabled testing for long-double and re-run the builders. Now both architectures successfully pass the package building process, but `mips` has [failed](https://buildd.debian.org/status/fetch.php?pkg=nfft&arch=mips&ver=3.3.2~rc2-2&stamp=1470189853). The log reveals that only the following testcase err'd:
```
nfft_online                     d = 2, N = [200  , 200                ], M = 50    nthreads = 2, init                        , m =  8, trafo          -> FAIL  1.4450309255438954E-05 ( 4.6629367034256575E-13)
```

Testing worked on the [previous](https://buildd.debian.org/status/fetch.php?pkg=nfft&arch=mips&ver=3.3.2~rc2-1&stamp=1467305820) iteration of the packaging, which could reveal a defect in the engineering of the tests.

**Comment by jenskeiner** [comment]
G'day,

thanks for the update. Issues on some problematic archs seem to be related to an incorrect definition of the machine epsilon. I'm still considering our options here as this seems to be a platform issue rather than a bug.

I'll try to look at the other issue below asap.

Best,


Jens

**Comment by ghisvail** [comment]
Closing following comment on #27
