### ISSUE TITLE
Add support for GNU Octave via MEX interface

### ISSUE THREAD

**Issue by tvolkmer** [NFFT/nfft#25]
On the webpage of [Marco Caliari](http://profs.scienze.univr.it/caliari/software.htm), there is a patch for compiling the NFFT MATLAB interface for GNU Octave. We should add this (in a modified way) to the autoconf/automake config files.

**Comment by caliarim** [comment]
Hi guys. I came here with the idea to ask for the possibility to install NFFT with GNU Octave (since I succeeded on it) and found that it is already in 3.3.2 milestone. Great! Feel free to use all the code you find on my webpage and do not hesitate to contact me, if needed.

**Comment by tvolkmer** [comment]
@caliarim Thank you very much! If possible, would you please have a look if the recent commit works for you on Ubuntu with GNU Octave?
I added the GNU Octave support to the autoconf scripts and changed your patch idea slightly: The GNU Octave 4.0.1 on my computer defines the macro `HAVE_OCTAVE` in its `mex.h`. So I use `#ifndef HAVE_OCTAVE` in `nfft/imex.h` instead of defining an own macro.


@jenskeiner Could you please have a look at the recent commit 1240acf?

**Comment by caliarim** [comment]
I tried on Mint 17.3 (Ubuntu 14.04), both Octave 4.0.2 and 4.1.0+. They both work (that is, simple_test works). "The directory where Octave header files are installed" can be obtained by mkoctfile -p OCTINCLUDEDIR. And mkoctfile is in the same package of the header files (liboctave-dev). I mean, the simple option --with-octave could be enough to compile the Octave mex interface. The only problem I see, is if more versions of Octave are installed.

**Comment by jenskeiner** [comment]
Will do. Thanks.

**Comment by tvolkmer** [comment]
Thank you both for your feedback.

The `simple_test.m` of `matlab/nfft` and `matlab/nnfft` work for me.
However, there is currently one issue with the `simple_test.m` of the NFFT on the sphere (`matlab/nfsft`). I think the user-defined data type `@f_hat` does not properly work on Octave. The other `projection.m` example seems to work.

@caliarim Thank you for this hint with `mkoctfile`.
Due to possible portability issues (Windows etc.), I would currently prefer to keep the `--with-octave` option.

@michaelquellmalz Would you please check if the GNU Octave support works on MinGW?

**Comment by caliarim** [comment]
matlab/nfsft/simple_test.m works for me, both octave 4.0.2 and 4.1.0+

**Comment by tvolkmer** [comment]
@caliarim Thanks for your tests. The problem occurs in MATLAB and Octave if I run `simple_test` first in `matlab/nfft` and then in `matlab/nfsft` as @michaelquellmalz pointed out to me. The script `matlab/nfft/simple_test.m` defines a variable `f_hat` which conflicts with the data type `@f_hat` used in `matlab/nfsft/`.

@michaelquellmalz observed another compiling problem (failed linking) on Windows (which also occurs on Linux if the octave MEX libraries are not in the `LD_LIBRARY_PATH`.
This means I should better add an option `--with-octave-libdir` to the autoconf macros.

**Comment by tvolkmer** [comment]
I changed the semantics of `--with-octave` a little bit and use `octave-config` and `mkoctfile`.
`--with-octave` is now the Octave root directory. Additionally, one may specify `--with-octave-libdir` and/or `--with-octave-includedir`.
If Octave is installed e.g. in `/opt/octave`, then the configure option should be `--with-octave=/opt/octave`.
If Octave is installed in the system as a standard package (e.g. in `/usr`), then simply
   `./configure --with-octave`
should work. In this case, `octave-config` is called (within `$PATH`) to determine the Octave path structure.

@caliarim The call `mkoctfile -p OCTINCLUDEDIR` gives wrong results on Windows. Instead, `octave-config -p OCTINCLUDEDIR` seems to work.

**Comment by michaelquellmalz** [comment]
On Windows this does not work out of the box since the libdir of the official Windows Octave binaries contain `liboctave.la`, which includes references to invalid paths that only exist in Linux like `/usr/lib/libcurl.la`. A simple workaround is to delete the files `/usr/lib/libcurl.la` and `liboctinterp.la`. Then the configure and compliation of NFFT works.

**Comment by ghisvail** [comment]
Keeping myself subscribed to this issue, since this could lead to the introduction of new Debian package, probably named `octave-nfft`. Thanks for working on an interface with octave for NFFT.

**Comment by michaelquellmalz** [comment]
Closing this issue because the Octave support works fine in Gnu Linux and the problem with Windows is an issue in Octave itself.

As temporary workaround (for Octave 4.0.3 in Windows), one can the files `liboctave.la` and `liboctinterp.la` in the subfolder `lib\octave\4.0.3` of the Octave installation.
