### ISSUE TITLE
Enable query of versioning information

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#27]
Please consider adding an additional function to the interface exporting versioning information. The rationales behind this are explained [here](http://lucumr.pocoo.org/2013/8/18/beautiful-native-libraries/), specifically in the "Stable ABI" section.

**Comment by jenskeiner** [comment]
Ok, will consider this. It absolutely makes sense. Just cannot give a definitive time frame yet.

**Comment by ghisvail** [comment]
Just to let you know, Debian will soon be entering its freeze period prior to the next stable release. If you plan to release a new stable release of NFFT, please consider doing it soonish so it leaves me time to update the packaging.

Cheers.

**Comment by jenskeiner** [comment]
I will try, but I'll only have more time starting next week. When's the deadline?

**Comment by ghisvail** [comment]
In a few months, but I prefer planning in advance as time will become scarce on my end as the end of the year is approaching.

**Comment by jenskeiner** [comment]
Ok, will try to complete the release asap.

**Comment by ghisvail** [comment]
Hi Jens, any news? :-)

**Comment by jenskeiner** [comment]
Not really I'm afraid. Time to work on this is scarce these days.

However, I think we just need to tag a new version as I have already added a new function called ..._get_version() weeks ago to develop.

The only other open point I still see is the build failures on a few architectures which are due to an incorrect definition of the machine epsilon. But this could be done later.

I can tag a new version next weekend earliest. Hope this helps. Let me know what you think.

**Comment by ghisvail** [comment]
Sounds good to me.

**Comment by jenskeiner** [comment]
Hi,

I have created a new pre-release, namely 3.3.2rc3. Can you check if there’s anything that would still need to be changed? If not, we can release quickly off the new release branch.

Please check out the new X(get_version)() API function to query versioning information. I hope this is more or less what you were asking for.

Note that the build is not yet fixed on all Debian architectures. Nevertheless we should close issue #24 as any obvious bugs on our side have been fixed.

We can open another ticket to track progress on the remaining architectures where it seems we need a workaround for deficiencies of the target (incorrect machine epsilon definition).

Cheers,


Jens

**Comment by ghisvail** [comment]
This issue is now addressed in 3.3.2rc3. Closing.
