### ISSUE TITLE
unsafe test of x values in nfft_check

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#3]
The following portion of code in ```nfft_check```:

```
  for (j = 0; j < ths->M_total * ths->d; j++)
  {
    if ((ths->x[j]<-K(0.5)) || (ths->x[j]>= K(0.5)))
    {
      return "ths->x out of range [-0.5,0.5)";
    }
  }
```

assumes that the ```plan->x``` pointer is always assigned. The following code segfaults in case one does not use the ```MALLOC_X``` flag and forgets to set ```x``` before calling ```nfft_check``` on the plan. Its execution should be conditional to a test for a non nullptr on ```ths->x```.

**Comment by jenskeiner** [comment]
Closed with #4.
