### ISSUE TITLE
Maximum number of plans too low

### ISSUE THREAD

**Issue by javroyva** [NFFT/nfft#31]
For some applications I have found that the maximum number of plans allowed is too low. I have managed to change the
#define PLANS_MAX 100 /* maximum number of plans */
in
nfft/nfftmex.c

But then I had to recompile the library. Would it be possible to make this limit higher, or to make it configurable?

Thanks.

**Comment by jenskeiner** [comment]
Hello Javier,

thanks for your message. The upper limit is rather arbitrary and should ideally be configurable. I will check if that can be implemented. Let's track progress here.

**Comment by javroyva** [comment]
Thanks for your answer!
If I can help in anything, please let me know.

**Comment by jenskeiner** [comment]
If you have any suggestions, feel free to create a pull request.

**Comment by tvolkmer** [comment]
@jenskeiner @michaelquellmalz
Please have a look at the suggested approach. If approved, I am going to add this to the remaining 7 mex interfaces.

**Comment by tvolkmer** [comment]
fixed in #53
