### ISSUE TITLE
configure problem when using Intel icc compiler with Intel MKL

### ISSUE THREAD

**Issue by tvolkmer** [NFFT/nfft#32]
Based on original bug report by Xiao Zhang via email.

When using the icc compiler with Intel MKL (configure option `CC="icc -mkl"`), the configure script incorrectly determines the `fftw3_LIBS` variable as `fftw3_LIBS='-lne required -lm'`.
Then, `make` fails later with the error message `ld: cannot find -lne `.

The problem is in the macros in `m4/ax_lib_fftw3.m4`, which do not handle the case when no `-l` library flag is required for `fftw_*` functions. For instance, this happens for Intel MKL.

**Comment by tvolkmer** [comment]
first try to solve this issue: commit 59c8ba4d83daf031a2e5d9296855fdcc1784c0cc

**Comment by jenskeiner** [comment]
Sorry I didn't look at this sooner. The change looks good to be merged to dev.

**Comment by tvolkmer** [comment]
merged back to dev and closing this issue
