### ISSUE TITLE
internal compiler error in fastsum.c | special make target for library?

### ISSUE THREAD

**Issue by coldfix** [NFFT/nfft#38]
Hi,

on a quick note, I get an internal compiler error when building with recent gcc: 7.1.1 20170630 (archlinux) while building `application/fastsum.c`:

```libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../include -I../../include -I/home/thomas/cern/MAD/lib/nfft3/../fftw3/api -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math -march=native -MT fastsum.lo -MD -MP -MF .deps/fastsum.Tpo -c fastsum.c -o fastsum.o
In function 'SearchTree':
cc1: internal compiler error: in gimplify_modify_expr, at gimplify.c:5637
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
```

This is probably just a hiccup that will be fixed in a future gcc version - nothing to take action within nfft itself. But for any others encountering the same problem: I only need the library not the applications, so instead of typing `make` to build all components I'm using the following series of commands to build only the library:

```bash
cd 3rdparty/cstripack
make
cd ../kernel
make
cd ..
make libnfft3.la
```

I'm not sure whether this is the best way to avoid building the applications, is there a suitable target to build only the library plus dependencies directly from the base directory?

**Comment by jenskeiner** [comment]
Should use --disable-examples and --disable-applications configure flags to avoid building anything that links against the library. Let me know if that works for you.

**Comment by coldfix** [comment]
Great, thanks! I'll close the issue now as I will probably not notice when the issue is fixed in gcc.
