### ISSUE TITLE
nfft_check should check f, f_hat and x for nullptr

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#4]
A direct extension of #3. Each pointers which are not managed by the plan internally, i.e. when their relevant ```MALLOC_$@``` flag was not set at initialization time, should be nullptr tested and return an appropriate error string.

**Comment by ghisvail** [comment]
Actually, having the plan without f, f_hat or x pointers set can be considered a consistant state, if their relevant MALLOC_{F, F_HAT, X} bit is unset. An inconsistent state, however, would be if any of these pointers were nullptr although MALLOC_{F, F_HAT, X} is set. Depends how much idiot proofing you want to add.

**Comment by jenskeiner** [comment]
the _check methods now return an error message if any of f, x, or f_hat are equal to 0. The methods are supposed to be only called just before any trafo/adjoint method.
