### ISSUE TITLE
Export API versioning information

### ISSUE THREAD

**Issue by jenskeiner** [NFFT/nfft#5]
Transferred from: https://github.com/NFFT/nfft_old/issues/20

It would be useful to export some versioning information of NFFT as part of the public API, so that the version of the API can be queried from an arbitrary NFFT DSO. This is of particular interest for me on the wrapping side, where the API changed from `3.2.x` to `3.3.0` forcing me to change the signature of the bindings.

As of today, I still need to ask the user for the version of the NFFT library or parse it from the filename which is fragile. With a proper export, querying the version would be facilitated by defining a light FFI with the signature of the export function or macro, bind the NFFT DSO to it and read the values. Based on the values, the appropriate signature for the bindings could then be chosen.

As to which solution, i.e. using an export routine `nfft_get_version(unsigned &major, unsigned &minor, unsigned &patch)`, or standard macro definition:
```
#define NFFT_VERSION_MAJOR 3
#define NFFT_VERSION_MINOR 3
#define NFFT_VERSION_PATCH 0
```
I shall let you guys choose.

Thanks for considering this issue and its appropriate resolution.

**Comment by tvolkmer** [comment]
I think we could add both, the macros in nfft3.h and the export routine
   `NFFT(get_version)(unsigned &major, unsigned &minor, unsigned &patch)`
to some file in `kernel/util/`.

@jenskeiner:
If we do so, open questions:
1. To which C file should we add the routine in `kernel/util/`?
2. Should we use the data type `unsigned` for all precisions?

**Comment by jenskeiner** [comment]
1. We should create a new file, e.g. `version.c`.
2. The datatype `unsigned` is safe across different floating-point precisions. It's size may change though depending on the architecture (32 vs. 64 bit). That shouldn't be a problem as mixing code for different architectures is, if not impossible, at least a bad idea.

**Comment by jenskeiner** [comment]
I've added a new method called `{nfft,nfftl,nfftf}_getversion()` which returns the desired version information. At this point, I don't see any additional value in exporting the version numbers via `nfft3.h`.
