### ISSUE TITLE
Remove or fix `iterS2`

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#54]
The application `iterS2` is currently not functional. The module `iterS2` was added in 2006 by @jenskeiner to the trunk. Since 2012 the file `applications/iterS2/README` says `THIS EXAMPLE IS CURRENTLY NOT FUNCTIONAL`. As far as I can see, the code has not been functional in any NFFT release (it first appeared in version 3.2.0). 

So I would suggest to remove the code of `iterS2` in the upcoming release unless anyone wants to provide a fix. Alternatively, we could just remove the folder from `make dist`. What is your opinion on this?

**Comment by jenskeiner** [comment]
Please remove from `make dist` for now. I will double-check the code before the next release after 3.4.0 and then we can decide its fate. Thanks.
