### ISSUE TITLE
Reconstruct the harmonics

### ISSUE THREAD

**Issue by vlavorini** [NFFT/nfft#69]
Hello,

that's probably a easy answer, but I lost myself in reading the formulae.

If I want to reconstruct a single harmonic, and so I have to extract frequency, phase and amplitude of it, how can I do? Just to complete, I'm working in one dimension and with the Python wrapper (pyNFFT), and I follow the example listed [here](https://github.com/ghisvail/pyNFFT/issues/26).

In the example the frequencies are extracted. So I tried to calculate the modules and angles from the relative complex numbers, but it turn out they are not amplitudes and phases.

Where I can find AMplitudes and Phases? Thank you!

**Comment by tvolkmer** [comment]
Since I do not know the exact representation you want to convert to, I can only give a general hint:
Please have a look at [https://en.wikipedia.org/wiki/Fourier_series#Definition](https://en.wikipedia.org/wiki/Fourier_series#Definition) for definition and conversion of different representations.
