### ISSUE TITLE
make install does not honour DESTDIR properly

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#7]
Steps to reproduce, after bootstrapping:

```
./configure --prefix=/usr
make
make DESTDIR=$HOME/local install
```

```install-data-hook``` fails to install the documentation and data content because it stills wants to put files in $prefix/$datarootdir (/usr/share) and $prefix/$docdir (/usr/share/doc/nfft), which is wrong. It should be in $destdir/$prefix/$datarootdir ($HOME/local/usr/share) and $destdir/$prefix/$docdir ($HOME/local/usr/share/doc/nfft).

**Comment by jenskeiner** [comment]
Should be fixed. Try again with the new tag.

**Comment by jenskeiner** [comment]
I think this can be closed now.
