### ISSUE TITLE
Prepare release 3.4.1

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#71]
This task is to prepare release 3.4.1.

**Comment by tvolkmer** [comment]
3.4.1-rc3 successfully tested on Linux+MacOS and by @michaelquellmalz on Windows.

**Comment by tvolkmer** [comment]
- Windows DLL and MEX files built by @michaelquellmalz and uploaded to nfft homepage.
   - Linux MEX files built on Scientific Linux 7 and uploaded to nfft homepage
   - release/3.4.1 merged to master and to develop
   - version number in configure.ac (develop) increased to 3.4.2-alpha
