### ISSUE TITLE
Add support for higher bandwidth in NFSFT and improve parallelization

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#72]
Currently, the NDSFT/NFSFT only works for bandwidths up to (appromately) N=1024. For higher bandwidths, the computations might return NaN (not a number) due to an arithmetic overflow.

Additionally, the precomputation in the OpenMP version requires more runtime and memory than it should. Currently, each thread performs the global precompution (`nfsft_precompute`) on its own and uses isolated arrays to store the results.

**Comment by tvolkmer** [comment]
fc9b02fcc87b5e661aeeddba4cdc9a9e9b66f48b various fixes

**Comment by michaelquellmalz** [comment]
The NFSFT now works with higher `N` (if the system supports x87 extended precision). Furthermore, the parallelization of `nfft_precompute` now shares the memory between threads and is also faster. This was included in #79
