### ISSUE TITLE
Compiled binaries do not work with Octave 4.4.1

### ISSUE THREAD

**Issue by michaelquellmalz** [NFFT/nfft#80]
The `mex`-binaries that were compiled with Octave 4.4.0 are incompatible the new Octave 4.4.1.

The reason is that the binaries rely on the library `liboctinterp-5.dll` while Octave 4.4.1 ships only the newer version `liboctinterp-6.dll`. This means that the incompatibility is in both directions, so `mex` files created with the new Octave won't work with the old version.

There seems to be no way to make the files run in both versions, see [an older forum discussion with Mike Miller](http://octave.1599824.n4.nabble.com/Oct-files-run-in-Octave-version-3-6-4-or-4-0-0-but-not-both-td4672690.html).

**Comment by tvolkmer** [comment]
Closing this issue since nfft-3.5.0 binaries are compiled against Octave 4.4.1 (liboctinterp-6.dll).
