### ISSUE TITLE
Test suite fails on 32-bit builds

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#9]
I have uploaded the source pkg for nfft-3.3.0.alpha3 on my Ubuntu PPA and let the build bots carry some builds for the current LTS releases.

They have all failed for i386 architectures, both on Ubuntu Precise and Trusty. According to the build logs in [here](https://launchpad.net/~ghisvail/+archive/ubuntu/nfft-dev/+build/6731263/+files/buildlog_ubuntu-precise-i386.nfft_3.3.0%7Ealpha3-1%7Eubuntu12.04.1%7Eppa1_FAILEDTOBUILD.txt.gz), it seems that some tolerances are a bit too strict in the b-spline and bessel function tests.

64-bit builds were fine.

**Comment by jenskeiner** [comment]
Error bounds have been adjusted. Can you test with 3.3.0 alpha 4?

**Comment by ghisvail** [comment]
Thanks, I'll make it run tonight.

**Comment by ghisvail** [comment]
I no longer get failed tests on i386 arch. Thanks.
