### ISSUE TITLE
Debian packaging for v3.3

### ISSUE THREAD

**Issue by jenskeiner** [NFFT/nfft#9]
Transferred from: https://github.com/NFFT/nfft_old/issues/8

Using this issue as a common thread for progress monitoring and discussion regarding packaging related problems.

TODO
--------
- [x] update packaging of v3.2 to v3.3
- [x] add multi-precision
- [x] add package tests
- [x] add documentation
- [x] submit package to experimental

**Comment by ghisvail** [comment]
Version 3.3 is in the archive. Please consider closing this issue.

**Comment by jenskeiner** [comment]
Closing this one. All tasks done.
